---
deployment:
  tasks:
    - php composer update
    - php composer dumpautoload -o
#    - php artisan migrate:fresh --seed
    - php artisan migrate
    - php artisan db:seed --class=ActionsTableSeeder
#    - php artisan migrate:old-data
    - php artisan view:clear
    - php artisan route:clear
    - php artisan optimize:clear
    - php artisan config:clear
    - php artisan cache:clear